version: "2.2"
services:
  fairmot:
    shm_size: '2gb'
    runtime: nvidia
    build:
      context: .
      args:
        IMAGE: nvidia/cuda:10.2-devel-ubuntu18.04
    ports:
      - "1234:22"
    volumes:
      - "./data:/data"
