version: "2.2"
services:
  devssh:
    shm_size: '2gb'
    runtime: nvidia
    build:
      context: .
      args:
        IMAGE: nvidia/cuda:11.3.0-cudnn8-devel-ubuntu18.04
    ports:
      - "1111:22"
    volumes:
      - "./data:/data"
